// Generated by CoffeeScript 1.6.3
(function() {
  var qtip;

  qtip = (function() {
    var div, hide, initialize, show;
    div = null;
    initialize = function() {
      var element, elements, _i, _len;
      elements = document.querySelectorAll('[title][data-qtip]');
      for (_i = 0, _len = elements.length; _i < _len; _i++) {
        element = elements[_i];
        element.addEventListener('touchstart', show);
        element.addEventListener('touchend', hide);
        element.addEventListener('mousedown', show);
        element.addEventListener('mouseup', hide);
      }
      div = document.createElement('div');
      div.id = 'qtip';
      return document.body.appendChild(div);
    };
    hide = function(event) {
      return div.classList.remove('visible');
    };
    show = function(event) {
      var element, offset;
      event.preventDefault();
      element = event.target;
      offset = element.getBoundingClientRect();
      div.innerHTML = element.getAttribute('title');
      div.style.cssText = "left: " + offset.left + "px;\ntop: " + (offset.top + element.offsetHeight) + "px;";
      return div.classList.add('visible');
    };
    return initialize();
  })();

}).call(this);
