// Generated by CoffeeScript 1.6.3
(function() {
  var qtip;

  qtip = (function() {
    var div, hide, initialize, show;
    div = null;
    initialize = function() {
      var elements;
      elements = document.querySelectorAll('[title][data-qtip]');
      elements.addEventListener('mousedown', show);
      elements.addEventListener('mouseup', hide);
      div = document.createElement('div');
      div.id = 'qtip';
      return document.appendChild(div);
    };
    hide = function(event) {
      return div.classList.remove('visible');
    };
    show = function(event) {
      var element, offset;
      element = event.target;
      offset = element.getBoundingClientRect();
      div.innerHTML = element.getAttribute('title');
      div.style.cssText = "left: " + offset.left + "px;\ntop: " + offset.top + "px;";
      return div.classList.add('visible');
    };
    return initialize();
  })();

}).call(this);
